In [3]:
import pandas as pd

data_file = 'data/ksprojects.csv'

kick_df = pd.read_csv(data_file)
print('Number of rows: {}'.format(kick_df.shape[0]))

Number of rows: 65418

In [5]:
bools = (kick_df['category'] == 'Documentary') & (kick_df['state'] == 'successful')
docs = kick_df.iloc[bools.values].sort_values(by='pledged', ascending=False)
docs.head(10)

,id,name,category,main_category,deadline,goal,launched,state,backers,country,usd_pledged,currency,pledged
11731,1078982332,BRIDEGROOM - An American Love Story,Documentary,Film & Video,2012-07-20 01:00:28,300000.0,2012-06-20 01:00:28,successful,6508,US,384376.0,USD,384376.0
24166,1162836718,"""The Wrecking Crew"" The Untold Story of Rock &...",Documentary,Film & Video,2013-12-21 08:59:00,250000.0,2013-10-30 21:06:34,successful,4245,US,313158.0,USD,313158.0
12127,1326363492,The Culture High,Documentary,Film & Video,2012-08-04 04:00:00,190000.0,2012-06-22 01:40:20,successful,3448,US,240022.0,USD,240022.0
61248,1203470139,Curious George Documentary,Documentary,Film & Video,2016-08-25 00:00:00,175000.0,2016-07-26 18:01:41,successful,1483,US,2028.0,USD,186010.0
28003,1205913248,ILEANA'S SMILE,Documentary,Film & Video,2014-05-21 09:05:00,133000.0,2014-04-21 09:05:00,successful,1173,US,177421.0,USD,177421.0
27402,1135999291,Rewind To Fast-Forward,Documentary,Film & Video,2014-05-01 07:59:00,137000.0,2014-03-30 13:35:31,successful,4395,US,176746.0,USD,176746.0
16243,1061853312,Linsanity: the Movie,Documentary,Film & Video,2013-02-16 00:00:00,117000.0,2013-01-15 19:46:34,successful,2102,US,167917.0,USD,167917.0
27268,1228065368,El Voto Hispano | The Documentary,Documentary,Film & Video,2014-04-27 08:15:23,158000.0,2014-03-18 07:15:23,successful,461,US,165401.0,USD,165401.0
43820,1194449879,"PlantPure Nation, a Documentary with Dr. T. Co...",Documentary,Film & Video,2015-05-14 17:41:41,150000.0,2015-03-15 16:41:41,successful,1099,US,163930.0,USD,163930.0
22237,122290911,The Killing of Tony Blair,Documentary,Film & Video,2013-10-07 18:17:14,50000.0,2013-08-28 18:17:14,successful,4459,GB,255150.0,GBP,163891.0